updates with actual hooks and manual builds

diff --git a/Dockerfile.release.full-debug b/Dockerfile.release.full-debug
--- a/Dockerfile.release.full-debug
+++ b/Dockerfile.release.full-debug
@@ -1,13 +1,6 @@
 ARG SOURCE_BRANCH
 FROM alexkuzko/omim:${SOURCE_BRANCH}-base as base
 
-RUN cd /srv/omim \
-    && (echo | ./configure.sh) \
-    && (./tools/unix/build_omim.sh -d) \
-    && (bash omim/tools/unix/run_tests.sh -b omim-build-debug && echo "TEST PASSED" || { echo "TEST FAILED"; true; })
-
-FROM mapsme/ci-linux
-
 ARG BRANCH
 ARG COMMIT
 ARG DATE
@@ -28,8 +21,10 @@ LABEL org.label-schema.schema-version="1.0" \
     org.label-schema.vcs-branch=$BRANCH \
     org.label-schema.vcs-ref=$COMMIT
 
-WORKDIR /srv
-
-COPY --from=base /srv/omim-build-debug /srv/omim-build-debug
+RUN cd /srv/omim \
+    && (echo | ./configure.sh) \
+    && (./tools/unix/build_omim.sh -d) \
+    && (cd /srv/omim/tools/python/maps_generator && pip3 install -r requirements.txt && /bin/cp -pf var/etc/map_generator.ini.default var/etc/map_generator.ini && cd /srv) \
+    && (bash /srv/omim/tools/unix/run_tests.sh -b /srv/omim-build-debug && echo "TEST PASSED" || { echo "TEST FAILED"; true; })
 
 CMD ["true"]
diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -14,11 +14,11 @@ if [[ ${DOCKERFILE_PATH} == 'Dockerfile.release' ]]; then
     echo "do not change the SOURCE_BRANCH"
 else
     if [[ ${SOURCE_BRANCH} =~ "-base" ]]; then
-    echo -n "chaning SOURCE_BRANCH from $SOURCE_BRANCH to "
+    echo -n "changing SOURCE_BRANCH from $SOURCE_BRANCH to "
     SOURCE_BRANCH=${SOURCE_BRANCH::-5}; # remove the -base from the source tag
     echo "$SOURCE_BRANCH"
     else
-    echo "SHOULD NOT HAPPENS, the SOURCE_BRANCH was not changed while should be"; exit 1;
+    echo "*** hook/build FAILED: SHOULD NOT HAPPENS, the SOURCE_BRANCH was not changed while should be"; exit 1;
     fi;
 fi
 
@@ -32,4 +32,4 @@ docker build \
   --build-arg BRANCH="${BRANCH}" \
   --build-arg DATE="${DATE}" \
   --build-arg SOURCE_BRANCH="${SOURCE_BRANCH}" \
--t "${DOCKER_REPO}:${DOCKER_TAG}" -f "${DOCKERFILE_PATH}" .
+-t "${DOCKER_REPO}:${DOCKER_TAG}" -f "${DOCKERFILE_PATH}" . || { echo "*** hooks/build FAILED"; exit 1; }
diff --git a/hooks/post_build b/hooks/post_build
--- a/hooks/post_build
+++ b/hooks/post_build
@@ -21,7 +21,7 @@ docker build \
   --build-arg BRANCH="${BRANCH}" \
   --build-arg DATE="${DATE}" \
   --build-arg SOURCE_BRANCH="${SOURCE_BRANCH}" \
--t "${DOCKER_REPO}:${SOURCE_BRANCH}-${I}" -f "${DOCKERFILE_PATH}" .
+-t "${DOCKER_REPO}:${SOURCE_BRANCH}-${I}" -f "${DOCKERFILE_PATH}.${I}" . || { echo "*** hooks/post_build FAILED"; exit 1; }
 done
 else
 echo "no custom post_build for base image"
diff --git a/hooks/post_push b/hooks/post_push
--- a/hooks/post_push
+++ b/hooks/post_push
@@ -9,9 +9,9 @@ done
 if [[ ${DOCKERFILE_PATH} == 'Dockerfile.release' ]]; then
 docker tag "${DOCKER_REPO}:${SOURCE_BRANCH}" "${DOCKER_REPO}:${SOURCE_BRANCH}-full" # we need to tag default image with full
 docker tag "${DOCKER_REPO}:${SOURCE_BRANCH}" "${DOCKER_REPO}:latest"
-docker push "${DOCKER_REPO}:latest"
+docker push "${DOCKER_REPO}:latest" || { echo "*** hooks/post_push FAILED"; exit 1; }
 for I in {full,full-debug,generator,generator-debug}; do
-docker push "${DOCKER_REPO}:${SOURCE_BRANCH}-${I}"
+docker push "${DOCKER_REPO}:${SOURCE_BRANCH}-${I}" || { echo "*** hooks/post_push FAILED"; exit 1; }
 done
 else
 echo "no custom post_push for base image"
